version: "3"
services:
  jupyternotebook:
    build: 
      #context: ./
      dockerfile: ./Dockerfile
    image: jupyter/datascience-notebook
    working_dir: /WORK
    volumes:
      - ./CODE:/WORK/CODE
      - ./DATA:/WORK/DATA
    ports:
      - "8888:8888"
    # 環境変数の設定
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''