version: '2'
services:
  # Neo4j server
  graph_db:
    container_name: 'graph-db'
    image: neo4j:4.4.16
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      #- NEO4J_dbms_memory_heap_max__size=1024M

  # XMAIL viewer
  xmail_viewer:
    container_name: 'xmail-viewer'
    build:
      context: ./
      dockerfile: ./xmail-viewer/Dockerfile
    volumes:
      - ./logs:/opt/app/xmail-viewer/logs
      - ./xmail-viewer/exports:/opt/app/xmail-viewer/exports
    #ports:
    #  - "3101:3000"
    environment:
      - GRAPH_DB_IP=graph_db
      - MAIML_TMP_DIR=/opt/app/xmail-viewer/models/tmp

  # file server for exported XMAIL
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "3101:80"
    volumes:
      - ./xmail-viewer/exports:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
